### ISSUE TITLE
Requirement failed in SinkAwareLoadEventHandler using pulsar-1.9.14.

### ISSUE THREAD

**Issue by galaxyeye** [platonai/exotic#10]
09:09:54.552 [r-worker-9] WARN  a.p.p.c.c.LoadComponent - Failed to invoke afterLoad | https://list.jd.com/list.html?cat=737,794,798&ev=4155_122030 -authToken b06test42c13cb000f74539b20be9550b8a1a90b9 -parse -refresh -requireSize 1 -scrollCount 25 -taskId r3 -taskTime 2022-09-05T01:00:00Z
java.lang.IllegalArgumentException: Failed requirement.
        at ai.platon.scent.crawl.urls.SinkAwareLoadEventHandler$5.invoke(ScrapeHyperlink.kt:53)
        at ai.platon.scent.crawl.urls.SinkAwareLoadEventHandler$5.invoke(ScrapeHyperlink.kt:52)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline$addLast$1.invoke(EventHandlers.kt:252)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline$addLast$1.invoke(EventHandlers.kt:251)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline.invoke(EventHandlers.kt:262)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline.invoke(EventHandlers.kt:239)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline$addLast$1.invoke(EventHandlers.kt:252)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline$addLast$1.invoke(EventHandlers.kt:251)
        at ai.platon.pulsar.crawl.WebPageHandlerPipeline.invoke(EventHandlers.kt:262)
        at ai.platon.pulsar.crawl.component.LoadComponent.afterLoad(LoadComponent.kt:342)
        at ai.platon.pulsar.crawl.component.LoadComponent.loadDeferred1(LoadComponent.kt:219)
        at ai.platon.pulsar.crawl.component.LoadComponent.access$loadDeferred1(LoadComponent.kt:40)
        at ai.platon.pulsar.crawl.component.LoadComponent$loadDeferred1$1.invokeSuspend(LoadComponent.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by platonai** [comment]
Fixed.
